version: '2'
# Note: Use scripts/runDockerSimulation.sh to make sure all environment variables are set

services:
  simulator:
    image: ${SUMATRA_IMAGE_SIMULATOR}
    command: "-hl --moduli sim_server --autoRef --maxSpeed --initialCommand PREPARE_KICKOFF_BLUE --waitForAis --playingTime 300 --timeout 3600"
    ports:
      - "8083:50543"

  ai-yellow:
    image: ${SUMATRA_IMAGE_YELLOW}
    command: "-hl --moduli sim_client --host simulator --aiYellow ${SUMATRA_AI_ADDITIONAL_ARGS}"
    environment:
      - SUMATRA_INFLUX_DB_PASSWORD=${SUMATRA_INFLUX_DB_PASSWORD}
      - SUMATRA_INFLUX_DB_USERNAME=${SUMATRA_INFLUX_DB_USERNAME}
    volumes:
      - "./temp/yellow/data:/Sumatra/data"

  ai-blue:
    image: ${SUMATRA_IMAGE_BLUE}
    command: "-hl --moduli sim_client --host simulator --aiBlue ${SUMATRA_AI_ADDITIONAL_ARGS}"
    environment:
      - SUMATRA_INFLUX_DB_PASSWORD=${SUMATRA_INFLUX_DB_PASSWORD}
      - SUMATRA_INFLUX_DB_USERNAME=${SUMATRA_INFLUX_DB_USERNAME}
    volumes:
      - "./temp/blue/data:/Sumatra/data"

  ssl-vision-client:
    image: robocupssl/ssl-vision-client:latest
    command: -visionAddress 224.5.23.2:11006 -visualizationAddress 224.5.23.2:11011
    ports:
      - "8082:8082"

  ssl-status-board:
    image: robocupssl/ssl-status-board:latest
    command: -refereeAddress 224.5.23.1:11003
    ports:
      - "8084:8082"
